# Generated by Django 6.0.1 on 2026-01-22 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_date_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
