# Generated by Django 6.0.1 on 2026-01-19 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_cart_id_alter_chartitem_unique_together'),
        ('product', '0002_alter_product_options_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChartItem',
            new_name='CartItem',
        ),
    ]
